export const teamCityMap = {
    Lal: "Los Angeles Lakers",
    Nyk: "New York Knicks",
    Bos: "Boston Celtics",
    Gol: "Golden State Warriors",
    Mia: "Miami Heat",
    Chi: "Chicago Bulls",
    Hou: "Houston Rockets",
    Phi: "Philadelphia 76ers",
    Dal: "Dallas Mavericks",
    San: "San Antonio Spurs",
    Tor: "Toronto Raptors",
    Okc: "Oklahoma City Thunder",
    Uta: "Utah Jazz",
    Den: "Denver Nuggets",
    Por: "Portland Trail Blazers",
    Lac: "Los Angeles Clippers",
    Atl: "Atlanta Hawks",
    Min: "Minnesota Timberwolves",
    Ind: "Indiana Pacers",
    Orl: "Orlando Magic",
    Nor: "New Orleans Pelicans",
    Sac: "Sacramento Kings",
    Bro: "Brooklyn Nets",
    Cha: "Charlotte Hornets",
    Det: "Detroit Pistons",
    Cle: "Cleveland Cavaliers",
    Mil: "Milwaukee Bucks",
    Pho: "Phoenix Suns",
    Was: "Washington Wizards",
    Mem: "Memphis Grizzlies",
    Nop: "New Orleans Pelicans",
};